const logger = require('../../config/logger');
const userService = require('../../services/userService');
const permissionService = require('../../services/permissionService');

function requireSystemAdmin(req) {
  if (req.user?.profile?.ROLE === 'System Admin') return;
  const error = new Error('Only the System Admin role can manage users.');
  error.statusCode = 403; error.code = 'FORBIDDEN'; throw error;
}
function requireLoggedInSystemAdmin(req) {
  if (req.user?.profile?.LOGGED_IN_ROLE === 'System Admin') return;
  const error = new Error('Only the System Admin role can manage users.');
  error.statusCode = 403; error.code = 'FORBIDDEN'; throw error;
}
function actorCode(req) { return req.user?.profile?.LOGGED_IN_CODE || req.user?.profile?.CODE; }
function validatePermissionSelections(selections) { return Array.isArray(selections) && selections.length > 0 && selections.every((selection) => selection && typeof selection.NAME === 'string' && selection.NAME.length > 0 && typeof selection.GRANTED === 'boolean'); }
async function listUsers(req, res, next) { try { requireSystemAdmin(req); const data = await userService.listUsers(req.query); res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate'); res.status(200).json({ success: true, data, correlationId: res.locals.correlationId || 'N/A' }); } catch (error) { next(error); } }
async function updateSystemActive(req, res, next) { try { requireSystemAdmin(req); if (typeof req.body?.enabled !== 'boolean') { const error = new Error('Request body must include boolean "enabled".'); error.statusCode = 400; error.code = 'VALIDATION_ERROR'; throw error; } const updatedBy = actorCode(req); if (!updatedBy) { const error = new Error('Authenticated user profile is missing an employee code.'); error.statusCode = 403; error.code = 'FORBIDDEN'; throw error; } const updated = await userService.setSystemActive(req.params.code, req.body.enabled, updatedBy); if (!updated) { const error = new Error(`User ${req.params.code} was not found.`); error.statusCode = 404; error.code = 'RESOURCE_NOT_FOUND'; throw error; } res.status(200).json({ success: true, data: { CODE: req.params.code, SYSTEM_ACTIVE: req.body.enabled }, correlationId: res.locals.correlationId || 'N/A' }); } catch (error) { next(error); } }
async function getUserDetail(req, res, next) { try { requireSystemAdmin(req); const data = await userService.getUserDetail(req.params.code); if (!data) { const error = new Error(`User ${req.params.code} was not found.`); error.statusCode = 404; error.code = 'RESOURCE_NOT_FOUND'; throw error; } res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate'); res.status(200).json({ success: true, data, correlationId: res.locals.correlationId || 'N/A' }); } catch (error) { next(error); } }
async function getUserPermissions(req, res, next) { try { requireSystemAdmin(req); const user = await userService.getUserDetail(req.params.code); if (!user) { const error = new Error(`User ${req.params.code} was not found.`); error.statusCode = 404; error.code = 'RESOURCE_NOT_FOUND'; throw error; } const permissions = await permissionService.getEffectivePermissions(req.params.code); res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate'); res.status(200).json({ success: true, data: { permissions }, correlationId: res.locals.correlationId || 'N/A' }); } catch (error) { next(error); } }
async function updateUserPermissions(req, res, next) { try { requireSystemAdmin(req); const selections = req.body?.permissions; if (!validatePermissionSelections(selections)) { const error = new Error('Request body must include a non-empty "permissions" array of { NAME, GRANTED } items.'); error.statusCode = 400; error.code = 'VALIDATION_ERROR'; throw error; } const user = await userService.getUserDetail(req.params.code); if (!user) { const error = new Error(`User ${req.params.code} was not found.`); error.statusCode = 404; error.code = 'RESOURCE_NOT_FOUND'; throw error; } const permissions = await permissionService.updateRolePermissions(req.params.code, selections); logger.info('User permissions updated', { correlationId: res.locals.correlationId, actorCode: actorCode(req), targetCode: req.params.code, count: selections.length }); res.status(200).json({ success: true, data: { permissions }, correlationId: res.locals.correlationId || 'N/A' }); } catch (error) { next(error); } }
async function setViewAs(req, res, next) { try { requireLoggedInSystemAdmin(req); const updatedBy = actorCode(req); if (!updatedBy) { const error = new Error('Authenticated user profile is missing an employee code.'); error.statusCode = 403; error.code = 'FORBIDDEN'; throw error; } await userService.setViewAs(updatedBy, req.params.code); logger.info('View As started', { correlationId: res.locals.correlationId, actorCode: updatedBy, targetCode: req.params.code }); res.status(200).json({ success: true, data: { VIEW_AS_CODE: req.params.code }, correlationId: res.locals.correlationId || 'N/A' }); } catch (error) { next(error); } }
async function clearViewAs(req, res, next) { try { requireLoggedInSystemAdmin(req); const updatedBy = actorCode(req); if (!updatedBy) { const error = new Error('Authenticated user profile is missing an employee code.'); error.statusCode = 403; error.code = 'FORBIDDEN'; throw error; } await userService.clearViewAs(updatedBy); logger.info('View As cleared', { correlationId: res.locals.correlationId, actorCode: updatedBy }); res.status(200).json({ success: true, data: { VIEW_AS_CODE: '' }, correlationId: res.locals.correlationId || 'N/A' }); } catch (error) { next(error); } }
module.exports = { listUsers, updateSystemActive, getUserDetail, getUserPermissions, updateUserPermissions, setViewAs, clearViewAs };
