IF COL_LENGTH('REQUESTS', 'IS_CLEAR_OUTSTANDING_BALANCE_PROPOSED') IS NULL
  ALTER TABLE REQUESTS ADD IS_CLEAR_OUTSTANDING_BALANCE_PROPOSED BIT NOT NULL CONSTRAINT DF_REQUESTS_CLEAR_OUTSTANDING_BALANCE_PROPOSED DEFAULT 0;

IF COL_LENGTH('REQUESTS', 'IS_WITHIN_APPROVED_LIMIT_PROPOSED') IS NULL
  ALTER TABLE REQUESTS ADD IS_WITHIN_APPROVED_LIMIT_PROPOSED BIT NOT NULL CONSTRAINT DF_REQUESTS_WITHIN_APPROVED_LIMIT_PROPOSED DEFAULT 0;

IF COL_LENGTH('REQUESTS', 'IS_BANK_GUARANTEE_PROPOSED') IS NULL
  ALTER TABLE REQUESTS ADD IS_BANK_GUARANTEE_PROPOSED BIT NOT NULL CONSTRAINT DF_REQUESTS_BANK_GUARANTEE_PROPOSED DEFAULT 0;

IF COL_LENGTH('REQUESTS', 'PROPOSED_BANK_GUARANTEE_AMOUNT') IS NULL
  ALTER TABLE REQUESTS ADD PROPOSED_BANK_GUARANTEE_AMOUNT DECIMAL(18, 4) NOT NULL CONSTRAINT DF_REQUESTS_BANK_GUARANTEE_AMOUNT DEFAULT 0;

IF COL_LENGTH('REQUESTS', 'IS_CASH_DEPOSIT_PROPOSED') IS NULL
  ALTER TABLE REQUESTS ADD IS_CASH_DEPOSIT_PROPOSED BIT NOT NULL CONSTRAINT DF_REQUESTS_CASH_DEPOSIT_PROPOSED DEFAULT 0;

IF COL_LENGTH('REQUESTS', 'PROPOSED_CASH_DEPOSIT_AMOUNT') IS NULL
  ALTER TABLE REQUESTS ADD PROPOSED_CASH_DEPOSIT_AMOUNT DECIMAL(18, 4) NOT NULL CONSTRAINT DF_REQUESTS_CASH_DEPOSIT_AMOUNT DEFAULT 0;