IF COL_LENGTH('APPROVALS', 'APPROVAL_STEP') IS NULL
BEGIN
  ALTER TABLE APPROVALS ADD APPROVAL_STEP INT NOT NULL
    CONSTRAINT DF_APPROVALS_APPROVAL_STEP DEFAULT 1 WITH VALUES;
END;

IF COL_LENGTH('APPROVALS', 'SORTING') IS NULL
BEGIN
  ALTER TABLE APPROVALS ADD SORTING INT NOT NULL
    CONSTRAINT DF_APPROVALS_SORTING DEFAULT 1 WITH VALUES;
END;

IF COL_LENGTH('APPROVALS', 'CREATED_BY') IS NULL
BEGIN
  ALTER TABLE APPROVALS ADD CREATED_BY INT NULL;
END;

IF COL_LENGTH('APPROVALS', 'CREATED_DATE') IS NULL
BEGIN
  ALTER TABLE APPROVALS ADD CREATED_DATE DATETIME NULL;
END;

;WITH ExistingApprovalOrder AS (
  SELECT ID,
         ROW_NUMBER() OVER (
           PARTITION BY REQUEST_ID
           ORDER BY COALESCE(CREATED_DATE, UPDATED_DATE), ID
         ) AS ROW_NUMBER
  FROM APPROVALS
  WHERE ENABLED = '1'
)
UPDATE APPROVALS
SET APPROVAL_STEP = ExistingApprovalOrder.ROW_NUMBER,
    SORTING = ExistingApprovalOrder.ROW_NUMBER
FROM APPROVALS
INNER JOIN ExistingApprovalOrder ON ExistingApprovalOrder.ID = APPROVALS.ID
WHERE APPROVALS.APPROVAL_STEP = 1
  AND APPROVALS.SORTING = 1;
