IF OBJECT_ID('USER_PERMISSIONS', 'U') IS NULL
BEGIN
  CREATE TABLE USER_PERMISSIONS (
    USER_ID NVARCHAR(255) NOT NULL,
    PERMISSION_ID NVARCHAR(255) NOT NULL,
    ENABLED NVARCHAR(1) NOT NULL
      CONSTRAINT DF_USER_PERMISSIONS_ENABLED DEFAULT N'1',
    CONSTRAINT PK_USER_PERMISSIONS PRIMARY KEY (USER_ID, PERMISSION_ID)
  );
END;
