IF COL_LENGTH('REQUESTS', 'SCORING_PROFITABILITY') IS NOT NULL
  ALTER TABLE REQUESTS ALTER COLUMN SCORING_PROFITABILITY VARCHAR(50) NULL;

IF COL_LENGTH('REQUESTS', 'SCORING_GROWTH') IS NOT NULL
  ALTER TABLE REQUESTS ALTER COLUMN SCORING_GROWTH VARCHAR(50) NULL;

IF COL_LENGTH('REQUESTS', 'SCORING_LIQUIDITY') IS NOT NULL
  ALTER TABLE REQUESTS ALTER COLUMN SCORING_LIQUIDITY VARCHAR(50) NULL;

IF COL_LENGTH('REQUESTS', 'SCORING_LEVERAGE') IS NOT NULL
  ALTER TABLE REQUESTS ALTER COLUMN SCORING_LEVERAGE VARCHAR(50) NULL;

IF COL_LENGTH('REQUESTS', 'EXISTING_PROFITABILITY') IS NULL
  ALTER TABLE REQUESTS ADD EXISTING_PROFITABILITY VARCHAR(50) NULL;

IF COL_LENGTH('REQUESTS', 'EXISTING_GROWTH') IS NULL
  ALTER TABLE REQUESTS ADD EXISTING_GROWTH VARCHAR(50) NULL;

IF COL_LENGTH('REQUESTS', 'EXISTING_LIQUIDITY') IS NULL
  ALTER TABLE REQUESTS ADD EXISTING_LIQUIDITY VARCHAR(50) NULL;

IF COL_LENGTH('REQUESTS', 'EXISTING_LEVERAGE') IS NULL
  ALTER TABLE REQUESTS ADD EXISTING_LEVERAGE VARCHAR(50) NULL;