IF COL_LENGTH('LOGS', 'REQUEST_ID') IS NULL
  ALTER TABLE LOGS ADD REQUEST_ID VARCHAR(128) NULL;

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_LOGS_REQUEST_ID_CREATED_DATE'
    AND object_id = OBJECT_ID('LOGS')
)
  EXEC('CREATE INDEX IX_LOGS_REQUEST_ID_CREATED_DATE ON LOGS (REQUEST_ID, CREATED_DATE DESC)');
