IF COL_LENGTH('ATTACHMENTS', 'STORAGE_PROVIDER') IS NULL
  ALTER TABLE ATTACHMENTS ADD STORAGE_PROVIDER VARCHAR(32) NULL;

IF COL_LENGTH('ATTACHMENTS', 'STORAGE_ITEM_ID') IS NULL
  ALTER TABLE ATTACHMENTS ADD STORAGE_ITEM_ID VARCHAR(255) NULL;

IF COL_LENGTH('ATTACHMENTS', 'STORAGE_DRIVE_ID') IS NULL
  ALTER TABLE ATTACHMENTS ADD STORAGE_DRIVE_ID VARCHAR(255) NULL;

IF COL_LENGTH('ATTACHMENTS', 'STORAGE_PATH') IS NULL
  ALTER TABLE ATTACHMENTS ADD STORAGE_PATH VARCHAR(1024) NULL;

IF COL_LENGTH('ATTACHMENTS', 'FILE_SIZE') IS NULL
  ALTER TABLE ATTACHMENTS ADD FILE_SIZE BIGINT NULL;

IF COL_LENGTH('ATTACHMENTS', 'MIME_TYPE') IS NULL
  ALTER TABLE ATTACHMENTS ADD MIME_TYPE VARCHAR(255) NULL;

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_ATTACHMENTS_STORAGE_ITEM_ID'
    AND object_id = OBJECT_ID('ATTACHMENTS')
)
  EXEC('CREATE INDEX IX_ATTACHMENTS_STORAGE_ITEM_ID ON ATTACHMENTS (STORAGE_ITEM_ID)');

UPDATE ATTACHMENTS
SET STORAGE_PROVIDER = 'FILE_SHARE',
    STORAGE_PATH = FILE_NAME
WHERE STORAGE_PROVIDER IS NULL;