const { DataTypes } = require('sequelize');

module.exports = (sequelize) =>
  sequelize.define(
    'Request',
    {
      ID: {
        type: DataTypes.STRING,
        primaryKey: true,
      },
      NO: DataTypes.STRING,
      CUSTOMER_NAME_TH: DataTypes.STRING,
      CUSTOMER_NAME_ENG: DataTypes.STRING,
      REQUESTED_SALES_GROUP: DataTypes.STRING,
      CRM_NO: DataTypes.STRING,
      SOLD_TO: DataTypes.STRING,
      CUSTOMER_TAX_NO: DataTypes.STRING,
      CUSTOMER_PHONE: DataTypes.STRING,
      CUSTOMER_FAX: DataTypes.STRING,
      CUSTOMER_REGISTERED_DATE: DataTypes.DATE,
      CUSTOMER_REGISTERED_CAPITAL_AMOUNT: DataTypes.DECIMAL(38, 0),
      CUSTOMER_SIZE_ID: DataTypes.STRING,
      CUSTOMER_BUSINESS_TYPE_INTER: DataTypes.TEXT,
      CUSTOMER_CUSTOMER_TYPE_INTER: DataTypes.TEXT,
      CUSTOMER_BUSINESS_TYPE_EXTER: DataTypes.TEXT,
      CUSTOMER_CUSTOMER_TYPE_EXTER: DataTypes.TEXT,
      CUSTOMER_SHAREHOLDERS: DataTypes.TEXT,
      CUSTOMER_DIRECTORS: DataTypes.TEXT,
      CUSTOMER_ADDRESS: DataTypes.STRING,
      DESCRIPTION: DataTypes.STRING,
      SEARCH_TERM: DataTypes.STRING,
      EXISTING_RATING_ID: DataTypes.STRING,
      REQUESTED_RATING_ID: DataTypes.STRING,
      REQUESTED_LIMIT_AMOUNT: DataTypes.DECIMAL(18, 4),
      REQUESTED_TERM_ID: DataTypes.STRING,
      PROPOSED_RATING_ID: DataTypes.STRING,
      PROPOSED_LIMIT_AMOUNT: DataTypes.DECIMAL(18, 4),
      PROPOSED_TERM_ID: DataTypes.STRING,
      PROPOSED_VALID_FROM: DataTypes.DATE,
      PROPOSED_VALID_TO: DataTypes.DATE,
      APPROVED_RATING_ID: DataTypes.STRING,
      APPROVED_LIMIT_AMOUNT: DataTypes.DECIMAL(18, 4),
      APPROVED_TERM_ID: DataTypes.STRING,
      IS_PERMANENT_PROPOSED: DataTypes.BOOLEAN,
      IS_TEMPORARY_PROPOSED: DataTypes.BOOLEAN,
      STATUS_ID: DataTypes.STRING,
      PROPOSED_DISPLAYED_NOTES: DataTypes.TEXT,
      PROPOSED_NOTES: DataTypes.TEXT,
      REQUESTED_BY: DataTypes.STRING,
      CREATED_DATE: DataTypes.DATE,
      UPDATED_BY: DataTypes.INTEGER,
      UPDATED_DATE: DataTypes.DATE,
      SCORING_PROFITABILITY: DataTypes.DECIMAL(18, 4),
      SCORING_GROWTH: DataTypes.DECIMAL(18, 4),
      SCORING_LIQUIDITY: DataTypes.DECIMAL(18, 4),
      SCORING_LEVERAGE: DataTypes.DECIMAL(18, 4),
      SCORING_RATING_ID: DataTypes.STRING,
      IS_PAY_IN_ADVANCE: DataTypes.BOOLEAN,
      IS_PAY_ON_TIME: DataTypes.BOOLEAN,
      IS_OVERDUE_GT_10_DAYS: DataTypes.BOOLEAN,
      IS_OVERDUE_GT_30_DAYS: DataTypes.BOOLEAN,
      IS_OVERDUE_GT_60_DAYS: DataTypes.BOOLEAN,
      IS_OVERDUE_GT_90_DAYS: DataTypes.BOOLEAN,
      ENABLED: DataTypes.STRING,
    },
    {
      tableName: 'REQUESTS',
      timestamps: false,
    },
  );
